### ISSUE TITLE
Accessors are not working on "Multi fields" using ".keyword"

### ISSUE THREAD

**Issue by alirezaImani-f4L3e** [pdphilip/laravel-elasticsearch#11]
## Describe the bug
I have a model named Audit and it has a `auditable_type` field which is multi field with types keyword and text . 
I tried to use accessors to format the retrevived `auditable_type` and realized that accessors are not working . even accessor function did not called . 

`Audit.php`
```php
<?php

...

class Audit extends Model
{
    ...

    public function getAuditableTypeAttribute(string $value)
    {
        return collect(array_filter(explode('\\', $value), function ($item) {
            return $item != null && $item != '';
        }))->last();
    }


}
```
`AuditRepository.php`

```php
$column = "auditable_type.keyword";
Audit::distinct($column)->get($column)->pluck([$column]); // we expect that accessor format the field .
```

## To Reproduce
Create a model using laravel-elasticsearch package and try to implement an accessor for a text field . 

## Expected behavior
We Expect that model accessor format the desired field correctly .

**Comment by pdphilip** [comment]
Hi, is hard to see what you're trying to do, but I can spot a few issues with what you have shared.

Your `getAuditableTypeAttribute()` accessor is faulty. Accessor methods do not have arguments, like `(string $value)`. They work as attributes of a current record (or an instantiated model class):

```php
  public function getFullNameAttribute()
  {
      return $this->first_name.' '.$this->last_name;   // returns $user->full_name
  }
```

Secondly, you can't perform database actions on accessors since these columns do not exist at a database level. They are handled by Laravel further up the stack. Getters create attributes from existing records, and setters manipulate fields before saving. 

If you try to find, sort, etc on an accessor-defined field with MySQL you will run into the same limitations.

**Comment by alirezaImani-f4L3e** [comment]
### About first tip  :
based on the [laravel@8 documentation](https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor) :
```php
<?php
 
namespace App\Models;
 
use Illuminate\Database\Eloquent\Model;
 
class User extends Model
{
    /**
     * Get the user's first name.
     *
     * @param  string  $value
     * @return string
     */
    public function getFirstNameAttribute($value)
    {
        return ucfirst($value);
    }
}
```
>As you can see, the original value of the column is passed to the accessor, allowing you to manipulate and return the value

### And about second tip : 
I have been mentioned that `auditable_type` is a `text field` on my `elasticsearch instance` and therefore it exists at databse level . 
<img width="575" alt="Screenshot 2024-01-30 at 14 03 39" src="https://github.com/pdphilip/laravel-elasticsearch/assets/83541857/69de412b-d265-4c32-9b3d-8d8c54fe8ea4">


Anyway I guess the problem is about useing `.keyword` because of that auditable_type is multi field .

**Comment by pdphilip** [comment]
I see, I was mistaken on both.

I did run a simple test on my end and it should work, this is what I did:

```php
public function getCodeAttribute(int $value)
{
    return $value + 1000000;
}
// code is a field with a possible value of 1 - 5
```
`UserLog::distinct('code')->get('code');` returned:
<img width="314" alt="Screenshot 2024-01-30 at 12 04 00" src="https://github.com/pdphilip/laravel-elasticsearch/assets/6921550/a4334f03-adcd-44cb-a509-8ea6a25260bc">

`UserLog::distinct('code')->get('code')->pluck(['code']);` produced:
<img width="157" alt="Screenshot 2024-01-30 at 12 04 09" src="https://github.com/pdphilip/laravel-elasticsearch/assets/6921550/6e365045-7063-41bc-a459-0ebd23bb43de">

The `.keyword` would throw it off for sure, what happens if you omit it? ie:
```php
$column = "auditable_type";
Audit::distinct($column)->get($column)->pluck([$column]);
```

**Comment by pdphilip** [comment]
Can you try re-index by having the field as a keyword first, then (assuming you want full-text search for this field) as text

```php
$index->keyword('auditable_type');
```
..then:
```php
$index->text('auditable_type');
```
Then the operation should use the keyword type as the default and you can omit `.keyword`

See: https://github.com/pdphilip/laravel-elasticsearch?tab=readme-ov-file#migrations

Let me know

**Comment by alirezaImani-f4L3e** [comment]
I have been re-index with your explained changes and `sorting` and `filtering` have been fixed . but in my search i have to use `.text` extenstion for this field .

**Comment by alirezaImani-f4L3e** [comment]
I'm using laravel@8 with pdphilip/laravel-elasticsearch@2.8 . 
Thanks for your attention .

**Comment by pdphilip** [comment]
@alirezaImani-f4L3e the latest version [v2.8.7](https://github.com/pdphilip/laravel-elasticsearch/releases/tag/v2.8.7) fixes this. You'll be able to execute distinct queries with the keyword flag, and the mutators will parse it correctly:

```php
$column = "auditable_type.keyword";
Audit::distinct()->get($column);
```
