### ISSUE TITLE
The raw response is not working after the last update

### ISSUE THREAD

**Issue by elsaid85** [pdphilip/laravel-elasticsearch#49]
Hi @DevYSM , update to the [latest release](https://github.com/pdphilip/laravel-elasticsearch/releases/tag/v4.0.4) and try the rawAggregation now. The update fixed the issue where only 1 agg result was being returned.

However, given the complexity of your query it may not return all the data you need. If that's the case then this update also has an upgrade on `rawSearch()` where you can add your body with a second parameter set to `true` to return the full unsanitized result. This will give you what you need, ex:

```php
YourModel::rawSearch($body,true)
```

Good luck!

_Originally posted by @pdphilip in https://github.com/pdphilip/laravel-elasticsearch/issues/35#issuecomment-2294989971_

**Comment by pdphilip** [comment]
Hi, v4.3.0 introduced a breaking change for `rawSearch`, see  [Release 4.3.0](https://github.com/pdphilip/laravel-elasticsearch/releases/tag/v4.3.0)  

> ## Breaking Change
> `rawSearch($bodyParams, $returnRaw = false)` has now been split into `rawSearch($bodyParams)` and `rawDsl($bodyParams)` where:
> - `rawSearch($bodyParams)` returns an ElasticCollection of results
> - `rawDsl($bodyParams)` returns the result body as is from Elasticsearch. Equivalent to $returnRaw = true previously. 

We cannot bump breaking changes to the next major versions (ex 5) since the major version is committed to the compatible Laravel version, but there should not be any more with 4.x. These changes are as a result of a package overhaul, sorry about that.
