### ISSUE TITLE
Help term()->search() with paginate

### ISSUE THREAD

**Issue by SergejGuruliov** [pdphilip/laravel-elasticsearch#50]
How to paginate term search
$result = Story::term($terms)->search();
$records = $result->paginate(10);
[Method Illuminate\Database\Eloquent\Collection::paginate does not exist.]

**Comment by pdphilip** [comment]
Hey @SergejGuruliov , documentation is in the process of being redone but you can do full text search now with normal `get()` type queries since [v4.2.0](https://github.com/pdphilip/laravel-elasticsearch/releases/tag/v4.2.0)

You can do:
```php
$result = Story::searchTerm($term)->paginate(10);
//Or
$result = Story::searchTerm($term)->searchTerm($term)->paginate(10);
$result = Story::searchTerm($term)->orSearchTerm($term)->paginate(10);
```
See  [v4.2.0](https://github.com/pdphilip/laravel-elasticsearch/releases/tag/v4.2.0) 

Cheers
